var data = [{
    src:'music/1.m4a',
    singer:'张宇',
    songTitle:'假行僧',
    album:'img/1.jpg'
},{
    src:'music/2.m4a',
    singer:'吴奇隆',
    songTitle:'祝你一路顺风',
    album:'img/2.png'
},{
    src:'music/3.m4a',
    singer:'张宇',
    songTitle:'离爱不远',
    album:'img/4.jpg'
},{
    src:'music/4.m4a',
    singer:'杨宗纬',
    songTitle:'越过山丘',
    album:'img/3.jpg'
}, {
    src:'music/5.m4a',
    singer:'李宗盛',
    songTitle:'给自己的歌',
    album:'img/5.jpg'
},{
    src:'music/6.m4a',
    singer:'李宗盛',
    songTitle:'我终于失去了你',
    album:'img/6.jpg'
},{
    src:'music/7.m4a',
    singer:'李宗盛',
    songTitle:'飘扬过海来看你',
    album:'img/7.jpg'
},{
    src:'music/8.m4a',
    singer:'李宗盛',
    songTitle:'我是真的爱你',
    album:'img/8.jpg'
},{
    src:'music/9.m4a',
    singer:'薛之谦',
    songTitle:'刚刚好',
    album:'img/9.jpg'
},{
    src:'music/10.m4a',
    singer:'罗大佑',
    songTitle:'你的样子',
    album:'img/10.jpg'
},{
    src:'music/11.m4a',
    singer:'林忆莲',
    songTitle:'为你我受冷风吹',
    album:'img/11.jpg'
}];
//